# Regresión logistica

**Qué es la regresión logística?** La regresión logística es un algoritmo de clasificación que se utiliza para predecir la probabilidad de que una instancia pertenezca a una clase específica. A diferencia de la regresión lineal, que predice valores continuos, la regresión logística se utiliza para problemas de clasificación binaria o multiclase.

## Ejercicio sobre Regresión Logística

Este notebook contiene un ejercicio práctico sobre regresión logística. 

Usaremos un dataset llamado Fake_Real_News_Dataset.csv, que contiene noticias clasificadas como falsas o verdaderas. El objetivo es construir un modelo de regresión logística que pueda predecir si una noticia es falsa o verdadera basándose en ciertas características.

### 1. Lectura de datos

In [2]:
import pandas as pd

In [6]:
# Cargamos el dataset
df_fake = pd.read_csv('datasets/Fake_Real_News_Dataset/Fake.csv')
df_real = pd.read_csv('datasets/Fake_Real_News_Dataset/True.csv')

In [7]:
# Hagamos una exploración rápida de los datos

df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
# Exploración de los datos reales

df_real.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [10]:
# Añadimos una columna "label" a cada dataframe para indicar si la noticia es falsa o verdadera

df_fake['label'] = 'False'
df_real['label'] = 'True'

In [21]:
# Ahora unimos ambos dataframes en uno solo

# ignore_index=True asegura que los índices se reenumeren en el dataframe combinado
df = pd.concat([df_real, df_fake], ignore_index=True)

In [22]:
# Comprobamos que los datos se han cargado correctamente y que la unión de los dataframes ha sido exitosa

print(f"Noticias reales: {len(df_real)}")
print(f"Noticias falsas: {len(df_fake)}")
print(f"Total de noticias: {len(df)}")

Noticias reales: 21417
Noticias falsas: 23481
Total de noticias: 44898

In [23]:
# Usamos df.head() para ver las primeras filas del dataframe combinado y asegurarnos de que todo está correcto
df.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",True
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",True
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",True
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",True
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",True

In [24]:
# Usamos df.tail() para ver las últimas filas del dataframe combinado y asegurarnos de que todo está correcto
df.tail()

,title,text,subject,date,label
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",False
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",False
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",False
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",False
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",False

### 2. Exploración de datos

El objetivo de esta sección es explorar el dataset para entender mejor su estructura y contenido. Esto incluye la visualización de las primeras filas del dataset, la verificación de valores nulos y la comprensión de la distribución de las clases.

In [27]:
# Analicemos una noticia real.

print("=" * 80)
print("Ejemplo de noticia real:")
print("=" * 80)
print(f"\nTitulo: {df[df['label']=='True'].iloc[0]['title']}")
print(f"\nTexto: {df[df['label']=='True'].iloc[0]['text'][:]}")

================================================================================
Ejemplo de noticia real:
================================================================================

Titulo: As U.S. budget fight looms, Republicans flip their fiscal script

Texto: WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support education, scientific research, infrastructure, public health and environmental protection. “The (Trump) administration has already been willing to say: ‘We’re going to increase non-defense discretionary spending ... by about 7 percent,’” Meadows, chairman of the small but influential House Freedom Caucus, said on the program. “Now, Democrats are saying that’s not enough, we need to give the government a pay raise of 10 to 11 percent. For a fiscal conservative, I don’t see where the rationale is. ... Eventually you run out of other people’s money,” he said. Meadows was among Republicans who voted in late December for their party’s debt-financed tax overhaul, which is expected to balloon the federal budget deficit and add about $1.5 trillion over 10 years to the $20 trillion national debt. “It’s interesting to hear Mark talk about fiscal responsibility,” Democratic U.S. Representative Joseph Crowley said on CBS. Crowley said the Republican tax bill would require the  United States to borrow $1.5 trillion, to be paid off by future generations, to finance tax cuts for corporations and the rich. “This is one of the least ... fiscally responsible bills we’ve ever seen passed in the history of the House of Representatives. I think we’re going to be paying for this for many, many years to come,” Crowley said. Republicans insist the tax package, the biggest U.S. tax overhaul in more than 30 years,  will boost the economy and job growth. House Speaker Paul Ryan, who also supported the tax bill, recently went further than Meadows, making clear in a radio interview that welfare or “entitlement reform,” as the party often calls it, would be a top Republican priority in 2018. In Republican parlance, “entitlement” programs mean food stamps, housing assistance, Medicare and Medicaid health insurance for the elderly, poor and disabled, as well as other programs created by Washington to assist the needy. Democrats seized on Ryan’s early December remarks, saying they showed Republicans would try to pay for their tax overhaul by seeking spending cuts for social programs. But the goals of House Republicans may have to take a back seat to the Senate, where the votes of some Democrats will be needed to approve a budget and prevent a government shutdown. Democrats will use their leverage in the Senate, which Republicans narrowly control, to defend both discretionary non-defense programs and social spending, while tackling the issue of the “Dreamers,” people brought illegally to the country as children. Trump in September put a March 2018 expiration date on the Deferred Action for Childhood Arrivals, or DACA, program, which protects the young immigrants from deportation and provides them with work permits. The president has said in recent Twitter messages he wants funding for his proposed Mexican border wall and other immigration law changes in exchange for agreeing to help the Dreamers. Representative Debbie Dingell told CBS she did not favor linking that issue to other policy objectives, such as wall funding. “We need to do DACA clean,” she said.  On Wednesday, Trump aides will meet with congressional leaders to discuss those issues. That will be followed by a weekend of strategy sessions for Trump and Republican leaders on Jan. 6 and 7, the White House said. Trump was also scheduled to meet on Sunday with Florida Republican Governor Rick Scott, who wants more emergency aid. The House has passed an $81 billion aid package after hurricanes in Florida, Texas and Puerto Rico, and wildfires in California. The package far exceeded the $44 billion requested by the Trump administration. The Senate has not yet voted on the aid.

In [33]:
# Analicemos una noticia falsa

print("=" * 80)
print("Ejemplo de noticia falsa:")
print("=" * 80)
print(f"\nTitulo: {df[df['label']=='False'].iloc[0]['title']}")
print(f"\nTexto: {df[df['label']=='False'].iloc[0]['text'][:500]}...")

================================================================================
Ejemplo de noticia falsa:
================================================================================

Titulo:  Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing

Texto: Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a gr...

**Observación:** Si analizamos las noticias falsas podemos ver que muchas contienen restos de HTML, URLs, caracteres especiales, etc. Esto es importante tenerlo en cuenta para la limpieza de datos y el preprocesamiento antes de entrenar el modelo.

### 3. Preprocesamiento de datos

Aquí nos encontramos con uno de los grandes retos del aprendizaje automático: la preparación de los datos. Esta etapa es crucial para garantizar que el modelo pueda aprender de manera efectiva. Incluye la limpieza de datos, la transformación de variables y la creación de nuevas características.

Las noticias pueden contener: 

- **Código HTML:** (etiquetas como `<p>`, `<a>`, `<div>`, etc.)
- **URLs:** enlaces a otros sitios web.
- **Simbolos de puntuación:** como comas, puntos, signos de interrogación, etc.
- **Palabras comunes:** que aparecen en todas las noticias y no ayudan a distinguir entre noticias falsas y verdaderas.(por ejemplo: "the", "is", "and", etc.)

Antes de entrenar el modelo, es importante limpiar y preprocesar los datos para eliminar estos elementos que no aportan valor al modelo. Esto puede incluir la eliminación de etiquetas HTML, la eliminación de URLs, la eliminación de símbolos de puntuación y la eliminación de palabras comunes.